[package]
name = "ai-oxide"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "ai_oxide"

[dependencies]
bytes = "1.10.1"
gstreamer = "0.23.5"
image = "0.25.5"
lapin = "2.5.0"
ndarray = "0.16.1"
object_store = { version = "0.12.0", features = ["http"] }
ort = { version = "=2.0.0-rc.10", default-features = false, features = ["std", "ndarray", "download-binaries", "half"]}
rc-zip-tokio = { version = "4.2.2", features = ["deflate64"] }
rust-s3 = { version = "0.35.1", features = ["with-tokio"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = [
  "io-util",
  "macros",
  "rt-multi-thread",
  "time",
] }
tokio-stream = "0.1.16"
tokio-util = { version = "0.7.12", features = ["io", "io-util"] }
tracing = "0.1.40"
tracing-bunyan-formatter = "0.3.9"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = [
  "env-filter",
  "registry",
] }
url = "2.5.4"
reqwest = "0.12.23"
gdal = { version = "0.18.0", features = ["ndarray"] }
num_cpus = "1.17.0"
imageproc = "0.25.0"
geo = "0.32.0"
half = "2.7.1"
num-traits = "0.2.19"
uuid = { version = "1.19.0", features = ["v4"] }
